/**
 * GitHub PR creation — fine-grained PAT flow.
 *
 * We never store the token. The caller passes it per-request; we use the
 * REST API to:
 *   1. Resolve the repo's default branch (or accept a base branch)
 *   2. Create a new branch from the base
 *   3. Add 2 files: a Markdown audit report + a Claude Code slash command
 *      that, when invoked, walks the codebase and applies the fixes
 *   4. Open a PR with a structured body listing every priority fix
 *
 * This avoids the "guess where their homepage source file lives" problem.
 * The PR is a real artifact the user can run in their own AI editor.
 */
import type { AuditResult } from '@/lib/audit'

const GH_API = 'https://api.github.com'

interface GhHeaders { 'Authorization': string; 'Accept': string; 'X-GitHub-Api-Version': string; 'User-Agent': string }
function headers(token: string): GhHeaders {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'GrowthHuntGEO/1.0',
  }
}

async function gh<T>(token: string, path: string, init: { method?: string; body?: unknown } = {}): Promise<T> {
  const res = await fetch(`${GH_API}${path}`, {
    method: init.method || 'GET',
    headers: { ...headers(token), 'Content-Type': 'application/json' },
    body: init.body ? JSON.stringify(init.body) : undefined,
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`GitHub ${init.method || 'GET'} ${path} → ${res.status}: ${text.slice(0, 240)}`)
  }
  return (await res.json()) as T
}

function host(url: string): string {
  try { return new URL(url).hostname.replace(/^www\./, '') } catch { return url }
}

function reportMarkdown(audit: AuditResult): string {
  const out: string[] = []
  out.push(`# GEO Audit — ${host(audit.url)}`)
  out.push(`Score: **${audit.overall_score}/100** (${audit.grade})  ·  ${new Date(audit.fetched_at).toISOString().slice(0, 10)}`)
  out.push('')
  out.push('## Engine compatibility')
  out.push('')
  for (const [k, v] of Object.entries(audit.engine_compatibility)) {
    out.push(`- ${k}: ${v}`)
  }
  out.push('')
  out.push('## Dimensions')
  out.push('')
  for (const d of audit.dimensions) {
    out.push(`- **${d.label}** — ${d.percent}% (weight ${d.weight})`)
  }
  if (audit.issues.length > 0) {
    out.push('')
    out.push('## Priority fixes')
    out.push('')
    audit.issues.forEach((i, n) => {
      out.push(`${n + 1}. **[${i.severity}] ${i.title}**`)
      if (i.explanation) out.push(`   - ${i.explanation}`)
      if (i.fix_suggestion) out.push(`   - Fix: ${i.fix_suggestion}`)
    })
  }
  out.push('')
  out.push('---')
  out.push('Generated by [GrowthHunt GEO](https://growthhunt.ai/geo). Run `/apply-geo-fixes` in Claude Code or pipe this file to Cursor/Windsurf to apply.')
  return out.join('\n')
}

function slashCommandMarkdown(audit: AuditResult, reportPath: string): string {
  return [
    '---',
    'description: Apply GEO audit fixes — improves AI answer-engine citations',
    '---',
    '',
    `# Apply GEO Fixes`,
    '',
    `Read \`${reportPath}\`. That report was generated by [GrowthHunt GEO](https://growthhunt.ai/geo) and audits ${audit.url} on 8 GEO dimensions.`,
    '',
    'For each "Priority fix" in that report, edit the appropriate files in this repository to implement the fix. Common patterns:',
    '',
    '- **Title not query-shaped** → update the page\'s `<title>` / metadata `title` to a "how does X work" or "what is X" form that includes the brand.',
    '- **Brand missing from H1 / meta description** → add it.',
    '- **No FAQ section** → add a `<FAQ />` component with 5–8 Q&A pairs, plus a `FAQPage` JSON-LD block.',
    '- **No datePublished / dateModified** → add both to the page\'s primary JSON-LD schema (and add a visible `<time>` element).',
    '- **No About/Contact link** → add to the footer.',
    '- **Heading skips (H2 → H4)** → renumber to keep hierarchy.',
    '- **No sourcing phrases / concrete data** → weave "According to..." attributions and specific numbers/percentages into the copy.',
    '',
    'Make small, focused edits. After applying, run `npm run build` (or the project\'s typecheck) and report what changed. Do NOT delete unrelated content.',
    '',
    `Re-audit at https://growthhunt.ai/geo?url=${encodeURIComponent(audit.url)} after the PR merges to confirm the score went up.`,
  ].join('\n')
}

function prBody(audit: AuditResult, reportPath: string, cmdPath: string): string {
  const top = audit.issues.slice(0, 8).map((i, n) => `${n + 1}. **[${i.severity}] ${i.title}** — ${i.fix_suggestion}`).join('\n')
  return [
    `## GEO audit — ${host(audit.url)}`,
    '',
    `Current score: **${audit.overall_score}/100** (${audit.grade}). Generated by [GrowthHunt GEO](https://growthhunt.ai/geo).`,
    '',
    '### What this PR adds',
    `- \`${reportPath}\` — the full audit report (8 dimensions, all checks, every fix)`,
    `- \`${cmdPath}\` — a Claude Code slash command that walks the codebase and applies the fixes`,
    '',
    '### Top priority fixes',
    '',
    top || '_(none)_',
    '',
    '### How to apply',
    '',
    `1. Open this branch in Claude Code, Cursor or Windsurf.`,
    `2. Run \`/apply-geo-fixes\` (Claude Code) or pipe \`${reportPath}\` to your agent.`,
    `3. Push edits to this branch — re-audit on merge.`,
    '',
    '_This PR was opened automatically by [GrowthHunt GEO](https://growthhunt.ai/geo/apply-fixes)._',
  ].join('\n')
}

export interface OpenPrInput {
  token: string         // GitHub fine-grained PAT (contents: write, pull requests: write on target repo)
  repo: string          // "owner/name"
  baseBranch?: string   // default: repo default
  audit: AuditResult
}

export interface OpenPrOutput {
  prUrl: string
  branch: string
  filesAdded: string[]
}

export async function openGeoPr(input: OpenPrInput): Promise<OpenPrOutput> {
  const { token, repo, audit } = input
  const [owner, name] = repo.split('/')
  if (!owner || !name) throw new Error(`Invalid repo "${repo}" — expected owner/name`)

  // 1. Resolve default branch
  const repoInfo = await gh<{ default_branch: string }>(token, `/repos/${owner}/${name}`)
  const base = input.baseBranch || repoInfo.default_branch

  // 2. Get the SHA of the base
  const baseRef = await gh<{ object: { sha: string } }>(token, `/repos/${owner}/${name}/git/refs/heads/${encodeURIComponent(base)}`)
  const baseSha = baseRef.object.sha

  // 3. Create new branch
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 16)
  const branch = `geo-audit/${stamp}`
  await gh(token, `/repos/${owner}/${name}/git/refs`, {
    method: 'POST',
    body: { ref: `refs/heads/${branch}`, sha: baseSha },
  })

  // 4. Add two files via the contents API
  const reportPath = `docs/geo-audit-${stamp}.md`
  const cmdPath = `.claude/commands/apply-geo-fixes.md`
  const reportContent = Buffer.from(reportMarkdown(audit), 'utf-8').toString('base64')
  const cmdContent = Buffer.from(slashCommandMarkdown(audit, reportPath), 'utf-8').toString('base64')

  await gh(token, `/repos/${owner}/${name}/contents/${reportPath}`, {
    method: 'PUT',
    body: {
      message: `geo: add audit report for ${host(audit.url)} (score ${audit.overall_score}/100)`,
      content: reportContent,
      branch,
    },
  })

  // The slash-command file may already exist; PUT requires a sha if updating.
  // Try-create; on 422 (file exists), fetch sha and update.
  try {
    await gh(token, `/repos/${owner}/${name}/contents/${cmdPath}`, {
      method: 'PUT',
      body: {
        message: `geo: add /apply-geo-fixes slash command`,
        content: cmdContent,
        branch,
      },
    })
  } catch (err) {
    const msg = (err as Error).message
    if (msg.includes('422') || msg.includes('sha')) {
      const existing = await gh<{ sha: string }>(token, `/repos/${owner}/${name}/contents/${cmdPath}?ref=${branch}`)
      await gh(token, `/repos/${owner}/${name}/contents/${cmdPath}`, {
        method: 'PUT',
        body: {
          message: `geo: refresh /apply-geo-fixes slash command`,
          content: cmdContent,
          branch,
          sha: existing.sha,
        },
      })
    } else {
      throw err
    }
  }

  // 5. Open the PR
  const pr = await gh<{ html_url: string; number: number }>(token, `/repos/${owner}/${name}/pulls`, {
    method: 'POST',
    body: {
      title: `GEO: ${host(audit.url)} — ${audit.overall_score}/100 → priority fixes`,
      head: branch,
      base,
      body: prBody(audit, reportPath, cmdPath),
      draft: false,
    },
  })

  return { prUrl: pr.html_url, branch, filesAdded: [reportPath, cmdPath] }
}
